// Generates the adire-inspired pattern tile used by the `adire` CSS utilities.
// Run: npx tsx scripts/adire.ts  → prints CSS to paste into globals.css
//
// Adire is the indigo resist-dyed cloth of Yoruba women dyers (notably in
// Abeokuta). Cloths are laid out as a grid of squares, each carrying a motif.
// This 64px tile nods to the three main techniques inside that grid:
//   top-left     oniko    – tie-dye: concentric rings around a dot
//   top-right    eleko    – starch-resist: a 3×3 cluster of dots
//   bottom-left  alabere  – stitch-resist: dashed diagonal stitch lines
//   bottom-right eleko    – a four-petal leaf around a centre dot

export function adireTile(stroke: string, background?: string, opacity = 1): string {
  const petals = [
    "M48 47C44.5 43.5 44.5 40 48 37.5C51.5 40 51.5 43.5 48 47Z", // up
    "M48 49C51.5 52.5 51.5 56 48 58.5C44.5 56 44.5 52.5 48 49Z", // down
    "M47 48C43.5 51.5 40 51.5 37.5 48C40 44.5 43.5 44.5 47 48Z", // left
    "M49 48C52.5 44.5 56 44.5 58.5 48C56 51.5 52.5 51.5 49 48Z", // right
  ].join("");
  const dots = [40, 48, 56]
    .flatMap((x) => [8, 16, 24].map((y) => `<circle cx='${x}' cy='${y}' r='1.7'/>`))
    .join("");

  return [
    `<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64' viewBox='0 0 64 64'>`,
    background ? `<rect width='64' height='64' fill='${background}'/>` : "",
    `<g opacity='${opacity}'>`,
    // The square grid that frames adire motifs.
    `<path d='M0 .5H64M.5 0V64M32 0V64M0 32H64' stroke='${stroke}' stroke-width='1' opacity='.55' fill='none'/>`,
    `<g fill='none' stroke='${stroke}' stroke-width='1.5' stroke-linecap='round'>`,
    `<circle cx='16' cy='16' r='11'/><circle cx='16' cy='16' r='6.5'/>`,
    `<path d='M5 59L27 37M5 48L16 37M16 59L27 48' stroke-dasharray='2.5 3'/>`,
    `<path d='${petals}'/>`,
    `</g>`,
    `<g fill='${stroke}'><circle cx='16' cy='16' r='2'/>${dots}<circle cx='48' cy='48' r='1.8'/></g>`,
    `</g></svg>`,
  ].join("");
}

const url = (svg: string) => `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;

// Deep indigo cloth with lighter indigo motifs (tuned so white text on it stays readable).
const INDIGO = "#1b2a5e";
const MOTIF = "#3d5299";

console.log(`/* Generated by scripts/adire.ts */
@utility adire {
  background-color: ${INDIGO};
  background-image: ${url(adireTile(MOTIF))};
  background-size: 64px 64px;
}
@utility adire-sm {
  background-color: ${INDIGO};
  background-image: ${url(adireTile(MOTIF))};
  background-size: 32px 32px;
}`);
